# Generated by Django 3.2.15 on 2023-07-08 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('lat', models.FloatField(max_length=10, verbose_name='Широта')),
                ('lon', models.FloatField(max_length=10, verbose_name='Долгота')),
                ('call_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания записи')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
