# Generated by Django 3.2.15 on 2023-07-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='lat',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='lon',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Долгота'),
        ),
    ]
