version: "3.3"


services:
  postgres:
    image: postgres:14.9
    container_name: postgres
    volumes:
      - /var/lib/postgresql/14/main:/var/lib/postgresql/14/main
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/14/main


  frontend:
    build:
      dockerfile: Dockerfile.frontend
      context: .
    container_name: frontend
    volumes:
      - /opt/star-burger/staticfiles/:/star-burger/staticfiles/
    ports:
      - 1234:1234
    command: >
      bash -c "./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./""


  backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    container_name: backend
    volumes:
      - /opt/star-burger/staticfiles/:/star-burger/staticfiles/
      - /opt/star-burger/media/:/star-burger/media/
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - frontend
      - postgres
    command: >
      bash -c "./manage.py collectstatic  --noinput &&
      ./manage.py makemigrations --noinput &&
      ./manage.py migrate --noinput &&
      ./manage.py load_locations --noinput &&
      gunicorn -w 5 -b 0.0.0.0:8081 star_burger.wsgi:application"
