version: "3.3"
services:
#   postgres:
#     image: postgres:15
#     container_name: postgres
#     volumes:
#       - ~/.pg/pg_data/star-burger:/var/lib/postgresql/data
#     env_file:
#       -.env
  backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    container_name: backend
    volumes:
      - /opt/star-burger/staticfiles/:/star-burger/staticfiles/
      - /opt/star-burger/media/:/star-burger/media/
    ports:
      - 8081:8081
    env_file:
      - .env
    command: >
      bash -c "gunicorn -w 5 -b 0.0.0.0:8081 star_burger.wsgi:application"
