version: "3.3"
services:
  postgres:
    image: postgres:14.9
    container_name: postgres
    restart: always
    volumes:
      - ${PGDATA}:${PGDATA}
    ports:
      - 5432:5432
    env_file:
      - .env


  frontend:
    build:
      dockerfile: Dockerfile.frontend
      context: .
    container_name: frontend
    volumes:
      - /opt/star-burger/staticfiles/:/star-burger/staticfiles/
    command: >
      bash -c "./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./""


  backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    container_name: backend
    restart: always
    volumes:
      - /opt/star-burger/staticfiles/:/star-burger/staticfiles/
      - /opt/star-burger/media/:/star-burger/media/
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      frontend:
          condition: service_completed_successfully
      postgres:
          condition: service_started
    command: >
      bash -c "gunicorn -w 5 -b 0.0.0.0:8081 star_burger.wsgi:application"
