version: "3.3"
services:
#   postgres:
#     image: postgres:15
#     container_name: postgres
#     volumes:
#       - ~/.pg/pg_data/star-burger:/var/lib/postgresql/data
#     env_file:
#       -.env
  django_service:
    image: django_service:latest
    container_name: django_service
    volumes:
      - /opt/star-burger/media/: /opt/star-burger/media/
      - /opt/star-burger/media/: /opt/star-burger/media/
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && manage.py migrate && gunicorn -w 5 -b 127.0.0.1:8081 star_burger.wsgi:application
