# Generated by Django 3.2.15 on 2023-05-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurateur', '0002_auto_20230520_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproductitem',
            options={'verbose_name': 'элемент заказа', 'verbose_name_plural': 'элементы заказа'},
        ),
    ]
