# Generated by Django 3.2.15 on 2023-07-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurateur', '0003_alter_orderproductitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='restaurateur.order', verbose_name='Заказ'),
        ),
    ]
