# Generated by Django 3.2.15 on 2023-07-04 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurateur', '0005_orderproductitem_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductitem',
            name='products_quantity',
        ),
        migrations.AddField(
            model_name='orderproductitem',
            name='products_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость товаров'),
            preserve_default=False,
        ),
    ]
