# Generated by Django 3.2.15 on 2023-07-05 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurateur', '0006_auto_20230704_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductitem',
            name='products_cost',
        ),
        migrations.AddField(
            model_name='orderproductitem',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена продукта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproductitem',
            name='product_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество продуктов'),
            preserve_default=False,
        ),
    ]
