# Generated by Django 3.2.15 on 2023-07-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurateur', '0007_auto_20230705_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NH', 'Не обработан'), ('HM', 'Обработан менеджером'), ('HR', 'Собран рестораном'), ('HD', 'Доставляется курьером'), ('DD', 'Доставлен')], db_index=True, default='NH', max_length=2, verbose_name='Статус'),
        ),
    ]
