# Generated by Django 3.2.15 on 2023-07-05 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurateur', '0009_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Дата и время звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Дата и время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='register_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время регистрации заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, db_index=True, max_length=300, verbose_name='Комментарий'),
        ),
    ]
