# Generated by Django 3.2.15 on 2023-07-11 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NH', 'Не обработан'), ('HM', 'Обработан менеджером'), ('HR', 'Собран рестораном'), ('HD', 'Доставляется курьером'), ('DD', 'Доставлен')], db_index=True, default='NH', max_length=2, verbose_name='Статус')),
                ('customer_first_name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('customer_last_name', models.CharField(max_length=50, verbose_name='Фамилия клиента')),
                ('customer_address', models.CharField(max_length=150, verbose_name='Адрес клиента')),
                ('customer_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона клиента')),
                ('payment_method', models.CharField(choices=[('NS', 'Не выбрано'), ('CH', 'Наличные'), ('CD', 'Карта')], db_index=True, default='NS', max_length=2, verbose_name='Способ оплаты')),
                ('register_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время регистрации заказа')),
                ('call_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время звонка')),
                ('deliver_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время доставки')),
                ('comment', models.TextField(blank=True, db_index=True, max_length=300, verbose_name='Комментарий')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан, который готовит заказ')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена продукта')),
                ('product_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество продуктов')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='foodcartapp.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='foodcartapp.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'элемент заказа',
                'verbose_name_plural': 'элементы заказа',
            },
        ),
    ]
